// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcS9Gc8WT1SmIcDI1ja4zxfDKHngDdTYo',
    appId: '1:728048816297:web:0cba310fd77dd6107319b8',
    messagingSenderId: '728048816297',
    projectId: 'fisiospakym-afff6',
    authDomain: 'fisiospakym-afff6.firebaseapp.com',
    databaseURL: 'https://fisiospakym-afff6-default-rtdb.firebaseio.com',
    storageBucket: 'fisiospakym-afff6.firebasestorage.app',
    measurementId: 'G-B56KS5NBRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdWrHu7Zann-DANB-pvI6xxKovul-OY28',
    appId: '1:728048816297:android:aebf799b765a55957319b8',
    messagingSenderId: '728048816297',
    projectId: 'fisiospakym-afff6',
    databaseURL: 'https://fisiospakym-afff6-default-rtdb.firebaseio.com',
    storageBucket: 'fisiospakym-afff6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDtBNhC9S0oixvYK3xFhF_vmv5z_w1Sa0',
    appId: '1:728048816297:ios:da99db5659c6292d7319b8',
    messagingSenderId: '728048816297',
    projectId: 'fisiospakym-afff6',
    databaseURL: 'https://fisiospakym-afff6-default-rtdb.firebaseio.com',
    storageBucket: 'fisiospakym-afff6.firebasestorage.app',
    androidClientId: '728048816297-jlpi6su175v3u96qtjm6j27bl5j0nsdb.apps.googleusercontent.com',
    iosBundleId: 'com.example.agendaFisioSpaKym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDtBNhC9S0oixvYK3xFhF_vmv5z_w1Sa0',
    appId: '1:728048816297:ios:da99db5659c6292d7319b8',
    messagingSenderId: '728048816297',
    projectId: 'fisiospakym-afff6',
    databaseURL: 'https://fisiospakym-afff6-default-rtdb.firebaseio.com',
    storageBucket: 'fisiospakym-afff6.firebasestorage.app',
    androidClientId: '728048816297-jlpi6su175v3u96qtjm6j27bl5j0nsdb.apps.googleusercontent.com',
    iosBundleId: 'com.example.agendaFisioSpaKym',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-CqDFbZ9VqNbWAHve7F2rSH_Ef0txYLY',
    appId: '1:728048816297:web:9e1ce7ce340a9d5a7319b8',
    messagingSenderId: '728048816297',
    projectId: 'fisiospakym-afff6',
    authDomain: 'fisiospakym-afff6.firebaseapp.com',
    databaseURL: 'https://fisiospakym-afff6-default-rtdb.firebaseio.com',
    storageBucket: 'fisiospakym-afff6.firebasestorage.app',
    measurementId: 'G-HWTJF2XQFM',
  );

}